### PR TITLE
Fixed Contact Page Responsive issue

### PR DESCRIPTION
**Pull request by crocmons**
Fixed Contact Page Responsive issue #346 

[screencast-crop-foresight-front-e9n6l8uyq-abhijeet141.vercel.app-2023.08.09-18_40_50.webm](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/106610322/a43dfdba-b834-48da-9ae1-088692898d37)

### CODE REVIEW

**Comment by abhijeet141** [comment]
@crocmons As the file hierarchy has been changed there are conflicts which can be resolved from your side only oncee you resolve the conflicts I will merge your PR

**Comment by crocmons** [comment]
> @crocmons As the file hierarchy has been changed there are conflicts which can be resolved from your side only oncee you resolve the conflicts I will merge your PR

yap, sure

**Comment by crocmons** [comment]
Actually, what should I change here?

**Comment by abhijeet141** [comment]
@abhijeet141 It will be better if you close this PR and Firstly pull the new changes and create a new branch then create a new PR.

**Pull request closed without merging**
