### PR TITLE
made some changes in frontend part.

### PR DESCRIPTION
**Pull request by Raghucharan16**
Hey @abhijeet141 I made some changes in couple of files to implement dark mode. I have got less knowledge in react and tried to spin this thing. I'm unable to install node as I hard reset my pc. so check out these commits if worthy, merge them and any issues on this please communicate so that i can recheck and resolve.
thank you

### CODE REVIEW

**Review by akuldeepj — COMMENTED** [review]
hey the website we are building is basically in dark theme right ?

**Comment by akuldeepj** [comment]
hey @Raghucharan16 instead of linking the css to all the pages currently just limit it to /form page since you made a darkmode for that

**Comment by akuldeepj** [comment]
Also the button in the preview isn't making any changes so could you also provide with the screenshots of the expected outcome

**Comment by Raghucharan16** [comment]
Hey @akuldeepj  Thanks for suggestion I'm on it. will update you soon.

**Pull request closed without merging**
