### PR TITLE
Adding Register Page

### PR DESCRIPTION
**Pull request by SubhamB2003**
solves #327 
@abhijeet141 Hey, I added the register. It's responsive and also has the option to go login page

image

image

### CODE REVIEW

**Comment by abhijeet141** [comment]
@SubhamB2003 You should wait for getting asigned one of the contributor is working on the UI of Login Page once his PR is merged you can make changes and create a new PR

**Comment by SubhamB2003** [comment]
> @SubhamB2003 You should wait for getting asigned one of the contributor is working on the UI of Login Page once his PR is merged you can make changes and create a new PR

Yes, actually I was working on the login page.  issue #309

**Comment by SubhamB2003** [comment]
Done.

**Comment by SubhamB2003** [comment]
@abhijeet141 Hey, please merge my prs

**Comment by abhijeet141** [comment]
@SubhamB2003 You need to resolve the conflicts once resolved I will merge your PR

**Comment by abhijeet141** [comment]
@SubhamB2003 No for file structure one contributor is already working

**Pull request merged**
