### PR TITLE
Create File Structure and Organize the files

### PR DESCRIPTION
**Pull request by SubhamB2003**
solves #222 
@abhijeet141 It is a humble request please merge this pr first after that you can merge other pr otherwise conflict occurs here. 

image

### CODE REVIEW

**Comment by SubhamB2003** [comment]
Again sorry their is same pull request already created. You can merge there pr first then if you think I can re organized it and update this pr

**Comment by abhijeet141** [comment]
@SubhamB2003 I will add this pr in last once all PR are merged don't worry about the PR just in last resolve all the conflicts

**Comment by SubhamB2003** [comment]
> @SubhamB2003 I will add this pr in last once all PR are merged don't worry about the PR just in last resolve all the conflicts

Thanks just ping me when all the pr merge then I resolve the conflicts.

**Comment by karthiknadar1204** [comment]
@abhijeet141  i had opened the very same pr before this pr, please look into it, this is happening for the second time with the same person

**Comment by abhijeet141** [comment]
@SubhamB2003 As I missed @karthiknadar1204 PR as he created the issue for the PR firstly I will merge his PR firstly and after that if you feel you can make changes you can do that

**Comment by SubhamB2003** [comment]
> @SubhamB2003 As I missed @karthiknadar1204 PR as he created the issue for the PR firstly I will merge his PR firstly and after that if you feel you can make changes you can do that

Yes, I also telling this on top. 
I can change after that

**Pull request closed without merging**
