### PR TITLE
Auth pages are not responsive

### PR DESCRIPTION
**Pull request by SubhamB2003**
solves #357 

image
image

### CODE REVIEW

**Comment by SubhamB2003** [comment]
@abhijeet141 Please check after 11.59 prs are not counted

**Comment by abhijeet141** [comment]
@SubhamB2003 You have implemented firebase in this branch only ?

**Comment by SubhamB2003** [comment]
> @SubhamB2003 You have implemented firebase in this branch only ?

No I added on Firebase branch

**Comment by abhijeet141** [comment]
@SubhamB2003 You have implemented everything on same branch which leads to a lot of confusion I need to revert this PR for now you need to do the changes on different branch

**Pull request merged**
