### PR TITLE
Adding Responsiveness

### PR DESCRIPTION
**Pull request by SubhamB2003**
Issue solved: #94 

Hey, @abhijeet141 can you please check

Make the navbar responsive
image

About page
image

Weather page
image

### CODE REVIEW

**Comment by abhijeet141** [comment]
Hey @SubhamB2003 There are some conflicts can you resolve those

**Comment by SubhamB2003** [comment]
> Hey @SubhamB2003 There are some conflicts can you resolve those

Yeah I can try

**Comment by SubhamB2003** [comment]
@abhijeet141 Hey, please check now.

**Comment by SubhamB2003** [comment]
> @abhijeet141 Hey, please check now. I do not understand how to resolve this but you can run my code It's properly ok and responsive.
Please check at least one

**Comment by abhijeet141** [comment]
@SubhamB2003 I have checked your code everything is fine but there are many conflicts don't worry give me some time I will resolve all conflicts and merge your PR

**Comment by SubhamB2003** [comment]
> 

Thank you

**Comment by abhijeet141** [comment]
Great work🚀

**Pull request merged**
