### PR TITLE
Made weather section navigation , and added the weather app

### PR DESCRIPTION
**Pull request by kharshita590**
#39 closes

### CODE REVIEW

**Comment by akuldeepj** [comment]
hey @kharshita590  I found a bug in your page actually when I type the page and hit enter it should give the output right? but it reloads the page instead so I had to go opt the button so you could fix it 🙂

**Comment by kharshita590** [comment]
@akuldeepj it means temperature and when you click on the button , then only thi function is called

**Comment by akuldeepj** [comment]
Ok so it's temperature in kelvin and I suggest you make the function work even with enter key

**Comment by abhijeet141** [comment]
@kharshita590  Great Work 🚀 Create a different Issue for this PR so that I can give points on this issue too.

**Comment by abhijeet141** [comment]
@akuldeepj No problem other contributors can enhance the features

**Comment by abhijeet141** [comment]
Closes #67

**Pull request merged**
