### PR TITLE
Added Backend Email Sending Component Using Nodejs Express Js to Send Email when needed to Reset password

### PR DESCRIPTION
**Pull request by GiriprasadKrishnamurthy**
Issue Number:#322

@Abhijeet I added the Email Sending Component in my project Using Node js and Express js
Please Consider my Pull Request You Can consider this as an extension or expansion to the project which can be made after syncing both the front end and backend 
As the coding period is coming to an end Please consider this Sir

### CODE REVIEW

**Comment by GiriprasadKrishnamurthy** [comment]
@abhijeet141  Pls accept this pull request Sir please

**Comment by GiriprasadKrishnamurthy** [comment]
@abhijeet141 Please accept this Sir being last coding day and extending code for email send Pls Sir

**Comment by GiriprasadKrishnamurthy** [comment]
Sir could you pls accept this @abhijeet141

**Comment by GiriprasadKrishnamurthy** [comment]
Sir could you pls consider this pull request @abhijeet141

**Comment by abhijeet141** [comment]
@GiriprasadKrishnamurthy don't worry I will review and merge the PR

**Pull request merged**
