### PR TITLE
About page revamp

### PR DESCRIPTION
**Pull request by karthiknadar1204**
After revamp:
Screenshot 2023-06-27 at 3 42 09 PM
Screenshot 2023-06-27 at 3 42 16 PM
Screenshot 2023-06-27 at 3 42 23 PM
Screenshot 2023-06-27 at 3 42 30 PM
Screenshot 2023-06-27 at 3 42 42 PM
Screenshot 2023-06-27 at 3 42 47 PM

I have added different components of the about page into containers and attached them to the opposite sides of the page, in the old layout, user might have gotten bored of watching the Constance in the view, this new layout can help keep the user engaged, it still has scope for improvement like adding some additional animation.

Clears issue #103

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
might have to change the colour of the container, @abhijeet141 If you have any colour in mind, please share, will add that, rest of it looks good to me

**Comment by karthiknadar1204** [comment]
Screenshot 2023-06-27 at 9 41 28 PM
Screenshot 2023-06-27 at 9 41 37 PM


Updated ui

**Comment by karthiknadar1204** [comment]
Also responsive

**Comment by karthiknadar1204** [comment]
@abhijeet141 Any update?

**Comment by abhijeet141** [comment]
@karthiknadar1204 
About page is not responsive and the div which you have created is not aligned at center have a look once and also visit the current about us page it is now fully responsive and it looks good for now.

**Comment by karthiknadar1204** [comment]
Should I make it responsive or will we close the issue?

**Comment by abhijeet141** [comment]
For now I am closing this PR

**Pull request closed without merging**
