### PR TITLE
Contact Form & contribution PR

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @abhijeet141 , 
Raise a new PR as you said. related issue #311  

### Video-
[Screencast from 06-08-23 03:33:04 PM IST.webm](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/121503426/155864e7-5e4f-402c-8d30-4b3e47ead138)

### ready to merge
```
Don't forget to give a good label.
```

### CODE REVIEW

**Comment by abhijeet141** [comment]
@SyedImtiyaz-1 Again the alignment is changed check for this issue 
image

**Comment by SyedImtiyaz-1** [comment]
> @SyedImtiyaz-1 Again the alignment is changed check for this issue image


okay I think the `:before` tag is the issue I have check the code and fixing this give me some time okay.

**Comment by SyedImtiyaz-1** [comment]
@abhijeet141 I code is repeated becuase of the conflict as per the previous merge of the other person as you can see here -
image


also I'm resolving the checks and working on this soon will push the code

**Comment by abhijeet141** [comment]
@SyedImtiyaz-1 Okay

**Pull request merged**
