### PR TITLE
Added images carousel in About page

### PR DESCRIPTION
**Pull request by Sameep002**
PR under #31 
Screenshot 2023-06-17 181620

### CODE REVIEW

**Comment by Sameep002** [comment]
@abhijeet141 pls check!!

**Comment by abhijeet141** [comment]
@Sameep002 can you try to resolve conflicts ?

**Comment by Sameep002** [comment]
@abhijeet141 resolved the conflicts 👍

**Comment by abhijeet141** [comment]
@Sameep002 Great !!

**Pull request merged**
