### PR TITLE
Weather page modified

### PR DESCRIPTION
**Pull request by kaashikaagrawal**
The weather page has been modified.
-Spelling mistake is rectified.
-UI made more attractive while matching the theme of the website.
image

### CODE REVIEW

**Comment by abhijeet141** [comment]
Great Work 🚀

**Comment by abhijeet141** [comment]
@kaashikaagrawal I need to revert the changes as changes are applied on every pages.

**Comment by kaashikaagrawal** [comment]
> @kaashikaagrawal I need to revert the changes as changes are applied on every pages.

I can work on the page again so that changes only occur on the weather page?

**Comment by abhijeet141** [comment]
> > @kaashikaagrawal I need to revert the changes as changes are applied on every pages.
> 
> I can work on the page again so that changes only occur on the weather page?

Yes you can

**Pull request merged**
