### PR TITLE
hierarchy

### PR DESCRIPTION
**Pull request by karthiknadar1204**
Improved the file hierarchy throughout the codebase to make it easier to navigate through the codebase

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
This could be counted under level3 right @abhijeet141 , has had some immense changes in the file paths

**Comment by karthiknadar1204** [comment]
@abhijeet141 This issue is resolving the much needed file hierarchy, please merge this first , it is creATING CONFLICTS

**Comment by karthiknadar1204** [comment]
#184

**Comment by abhijeet141** [comment]
@karthiknadar1204 once I merge remaining PR i will message you just resolve the conflcts I will merge your PR

**Comment by abhijeet141** [comment]
@karthiknadar1204 Resolve these conflicts I will merge your PR first

**Comment by abhijeet141** [comment]
@karthiknadar1204 Are you working on the conflicts ?

**Comment by karthiknadar1204** [comment]
Will update the file hierarchy completely tonight, please merge it tomorrow morning first thing so that we can avoid merge conflicts and ask the contributors to pull the changes before moving forward

**Comment by abhijeet141** [comment]
@karthiknadar1204 Any update ?

**Comment by karthiknadar1204** [comment]
Ready,will push the changes all today evening by 5:00 pm
Thank you

**Pull request closed without merging**
