### PR TITLE
Set up the active links and corrected some spelling mistakes

### PR DESCRIPTION
**Pull request by nitin-pandita**
Please have a look, i have added the active links for the navbar

### CODE REVIEW

**Comment by abhijeet141** [comment]
@nitin-pandita have you created an issue for this ?

**Comment by abhijeet141** [comment]
@nitin-pandita once resolve the conflicts by today then I will merge this PR

**Comment by nitin-pandita** [comment]
I have sorted all the conflicts please merge it now

**Comment by nitin-pandita** [comment]
Everything works fine now

**Comment by nitin-pandita** [comment]
Please merge the request

**Comment by nitin-pandita** [comment]
Hey @abhijeet141 please merge it

**Review by nitin-pandita — COMMENTED** [review]
i have made the changes please have a look

**Pull request closed without merging**
