### PR TITLE
Newhomepage

### LINKED ISSUE #5: Unreadable home page
@abhijeet141  I would like to work on the homepage for making the UI(button) better,make changes in the home to be more apeling and the text readable  as it is not having any different font from the video and it even overlaps with it and changing the button as it doesn't suit this background could you assign this task to me under GSSoC'23

image

### PR DESCRIPTION
**Pull request by akuldeepj**
I made a few changes to make it a user friendly page close #5 
**Changes Made: **
-Added a background
-Made a NavBar which can be activated when next pages are made
-added a TypeWrite effect
-made It compatible with Mobiles
-Added a Glass effect for the content

### CODE REVIEW

**Comment by akuldeepj** [comment]
image

**Comment by akuldeepj** [comment]
mobile version :
image

**Comment by abhijeet141** [comment]
@akuldeepj Great work 🚀Looks good for now. Thank you for your contribution!

**Comment by abhijeet141** [comment]
@tajmalnas has this PR affected any changes ?

**Comment by akuldeepj** [comment]
also @tajmalnas thanks for the suggestion and I think you forgot to change the font colour for the form as it now has white colour and it can't be readable on glass effect

**Comment by tajmalnas** [comment]
@akuldeepj welcome and also thanks for your suggestion

**Pull request merged**
