### PR TITLE
Add Contributor Page

### PR DESCRIPTION
**Pull request by SubhamB2003**
solves #180 
Hey, I added the contributor page and also improve the navbar UI now it looks good.

### CODE REVIEW

**Comment by abhijeet141** [comment]
@SubhamB2003 A similar PR already exist on the same Issue

**Comment by SubhamB2003** [comment]
@abhijeet141 Can you please add the labels? Otherwise they are not counting this PR.

**Comment by SubhamB2003** [comment]
> @SubhamB2003 A similar PR already exist on the same Issue
😥 can I get the point?

**Comment by karthiknadar1204** [comment]
@abhijeet141 I already have a pr for the same issue, had a small issue with the link, should I proceed or abandon the issue, had made the pr long time ago...

**Comment by abhijeet141** [comment]
@karthiknadar1204 I am sorry that was my mistake I don't know how I merged this PR and I am not able to revert this PR also can you create a dummy PR I will assign you the Level for this PR #227

**Comment by abhijeet141** [comment]
> > @SubhamB2003 A similar PR already exist on the same Issue
> 
> 😥 Can I get the point?

As this was my mistake I have given the points but please from next time take care that you are not creating similar issue

**Comment by karthiknadar1204** [comment]
Dummy pr as in ?
I created another pr for the contributors page,a better designed one with appropriate spacing and responsiveness,please check the preview for #227

**Comment by abhijeet141** [comment]
@karthiknadar1204 Actually the main issue is I am not able to revert this PR If I will merge your than there will be 2 contributor section. One thing you can do is create a new issue to remove one of the section

**Comment by karthiknadar1204** [comment]
Ah no,i pulled these changes and have overwritten the entire existing code with proper responsiveness and design

**Comment by karthiknadar1204** [comment]
So it shouldn't pose any issue,

**Comment by abhijeet141** [comment]
@karthiknadar1204 Yeah then there will be no issue

**Comment by SubhamB2003** [comment]
> 

@abhijeet141 Yeah, I am really sorry next time I am more careful.

**Pull request merged**
