### PR TITLE
Crop recommendation section updated

### LINKED ISSUE #157: Improve UI for the crop recommendation page.
I would like to change the UI for the crop recommendation page by adding some effects and by increasing visualizations.
So,please assign this task to me under gssoc'23
image

### PR DESCRIPTION
**Pull request by Pragati-3003**
I have the crop recommendation page for the website .
Closes #157
Kindly check and lemme know if you wanna any other changes.

### CODE REVIEW

**Comment by Pragati-3003** [comment]
> I have the crop recommendation page for the website . Closes #157 Kindly check and lemme know if you wanna any other changes.

@abhijeet141 ,please review and merge the PR.

**Comment by Pragati-3003** [comment]
@abhijeet141 , please merge the  PR.

**Comment by Pragati-3003** [comment]
@abhijeet141 ,Kindly  look into this PR .

**Comment by abhijeet141** [comment]
@Pragati-3003 Sorry as now Crop Recommendation UI has been changed I can't merge this PR but you can create a dummy PR I will assign you points for this PR

**Pull request closed without merging**
