### PR TITLE
added more attributes of weather condition

### PR DESCRIPTION
**Pull request by Owais24code**
@abhijeet141 review the commit and please let me if you want to add any further changes.

### CODE REVIEW

**Comment by abhijeet141** [comment]
@Owais24code Great Work but the changes are not getting reflected on the website have a look at this issue 
image

**Comment by Owais24code** [comment]
> @Owais24code Great Work but the changes are not getting reflected on the website have a look at this issue image
@abhijeet141 
okay can redesign the whole page as if the API key is not properly working .

**Comment by Owais24code** [comment]
@abhijeet141 
I request you let me redesign the weather page and i assure you that it will look good.

**Comment by abhijeet141** [comment]
> @abhijeet141 I request you let me redesign the weather page and i assure you that it will look good.

@Owais24code Okay

**Comment by Owais24code** [comment]
@abhijeet141 please review the changes 
Screenshot 2023-07-11 103913

**Comment by abhijeet141** [comment]
@Owais24code Sorry as now Weather UI has been changed I can't merge this PR but you can create a dummy PR I will assign you points for this PR

**Pull request closed without merging**
