### PR TITLE
Add firebase Authentication

### PR DESCRIPTION
**Pull request by SubhamB2003**
solves #352 
@abhijeet141 added email and password registration and Google auth registration.

### CODE REVIEW

**Comment by SubhamB2003** [comment]
> 

Give me 5min i resolved it

**Comment by SubhamB2003** [comment]
@abhijeet141 Can you please merge this pr first

**Comment by SubhamB2003** [comment]
@abhijeet141 Please check

**Comment by SubhamB2003** [comment]
@abhijeet141 Hey, It's humble request please merge my pr within 11.59 PM

**Comment by abhijeet141** [comment]
@SubhamB2003 Deployment has been failed

**Comment by SubhamB2003** [comment]
> @SubhamB2003 Deployment has been failed 

Hey, there is no credentials you need to add your firebase credentials

**Comment by SubhamB2003** [comment]
@abhijeet141 you forgot to add labels in this branch

**Pull request merged**
