### PR TITLE
Added Favicon

### PR DESCRIPTION
**Pull request by Akshatchaube01**

### CODE REVIEW

**Comment by Akshatchaube01** [comment]
issue #4

**Comment by Akshatchaube01** [comment]
Why is the deployment failing ?

**Comment by abhijeet141** [comment]
Hi @Akshatchaube01 
There is a missing double quote once rectify that and create a new commit 
image

**Comment by Akshatchaube01** [comment]
Hi @abhijeet141 , I have made the changes.

**Comment by abhijeet141** [comment]
Great 🚀

**Comment by Akshatchaube01** [comment]
@abhijeet141 This is a level 1 PR right ?

**Comment by abhijeet141** [comment]
@Akshatchaube01 Yes

**Pull request merged**
