### PR TITLE
Implemented Fresh Dark mode on each page #254

### PR DESCRIPTION
**Pull request by Tisha6661**
Fixes issue :  #254 
@abhijeet141 , this is a new branch so i had to create a new pr . the older one now have very large number of conflicts due to major changes in the codebase

### CODE REVIEW

**Comment by Tisha6661** [comment]
These changes are implemented in the dark mode 

image
image
image
image
image
image

Many changes could not be achieved as the codebase is too messy , 
for example currently there are two files co-existing for the weather Page
image

use of table in the contributors page rather than using map 
image

These wrong practices are avoiding implementing dark mode properly .

**Comment by abhijeet141** [comment]
@Tisha6661 Everything looks fine but can you implement the dark mode at home page also ?

**Comment by Tisha6661** [comment]
image
image
image

I had implemented basic change the blue strip cannot be removed as the changes had been made in the root body 


image
image

**Comment by Tisha6661** [comment]
@abhijeet141 please do review the changes

**Comment by abhijeet141** [comment]
@Tisha6661 a small change needed by default the page should be in dark mode only and on the login page dark mode is not working

**Comment by Tisha6661** [comment]
Sorry had missed something @abhijeet141  please be online , implementing the changes in a few minutes

**Comment by Tisha6661** [comment]
image
All the changes are made

**Comment by abhijeet141** [comment]
@Tisha6661 Have you pushed the new changes ?

**Comment by Tisha6661** [comment]
yess

**Comment by Tisha6661** [comment]
Its Live now

**Comment by Tisha6661** [comment]
@abhijeet141 please review the changes

**Comment by abhijeet141** [comment]
Everything looks fine now Great work 🚀

**Pull request merged**
