### PR TITLE
Fixed the Contribution Page Issue

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @abhijeet141 ,
I have fixed the contribution issue.

Fixed Issue #296 

### Video - 
[Screencast from 02-08-23 06:58:26 PM IST.webm](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/121503426/0b6716b5-da11-465b-af1a-a223c32fa748)

### CODE REVIEW

**Comment by abhijeet141** [comment]
Great Work 🚀

**Comment by abhijeet141** [comment]
@SyedImtiyaz-1 I need to revert this PR as I think it is changing the alignment of website

**Comment by SyedImtiyaz-1** [comment]
> @SyedImtiyaz-1 I need to revert this PR as I think it is changing the alignment of website

okay will check and tag you in sometime

**Comment by SyedImtiyaz-1** [comment]
@abhijeet141 , I have fixed the alignmetn issue you can merge this now.

**Comment by abhijeet141** [comment]
@SyedImtiyaz-1 Create two different PR one for the contact us section and for fixing the contributor page I am removing the labels for now from this PR once you create both PR I will assign you the labels

**Comment by SyedImtiyaz-1** [comment]
> @SyedImtiyaz-1 Create two different PR one for the contact us section and for fixing the contributor page I am removing the labels for now from this PR once you create both PR I will assign you the labels

I have raised one PR including Contact page and contribution fixes #311

**Pull request merged**
